### PR TITLE
Page speed optimizations

### PR DESCRIPTION
**Pull request by ajayns**
Live: http://detailed-temper.surge.sh

### CODE REVIEW

**Comment by ajayns** [comment]
Did you check out the Lighthouse score? Locally it seems to be registering my service worker but surge doesn't seem to allow it. Probably an HTTPS issue?

cc / @utkarsh-var if possible we'll merge this and deploy to an HTTPS server

**Comment by apollonian11** [comment]
yeah, sw register fails on non HTTPS websites.
Lighthouse was green all the way.

**Comment by ajayns** [comment]
screenshot from 2018-08-25 21-34-00

**Comment by apollonian11** [comment]
Desktop:

screen shot 2018-08-26 at 9 09 52 am


Mobile:

screen shot 2018-08-26 at 9 11 40 am

**Comment by ajayns** [comment]
I think you might wanna retry the mobile one, I'm getting a way higher score @apollonian11

**Comment by ajayns** [comment]
also if you've got any changes you'd recommend please let me know, else let's merge this.

**Comment by apollonian11** [comment]
This definitely improves the score, so I think we should merge it. 👍

**Pull request merged**
